apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-exporter
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - mysql
  selector:
    matchLabels:
      app: mysql-exporter
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
