apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: automation-gateway
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: automation-gateway
  namespaceSelector:
    matchNames:
    - apps
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
